### ISSUE TITLE
Comprehensive TODO List

### ISSUE THREAD

**Issue by abhabongse** [abhabongse/fuzzymatch-go#1]
- [x] Rename package: `canonical` → `sanitize`
- [x] Rename package: `candidacy` → `candidate`
- [x] Standardize various terminology for string edit distance (such as character-distance metric vs. string distance vs. edit distance).
- [x] Review functional options in package `factory` 
- [x] Think of how to separate functions which apply to very generic strings and purpose-specific strings (strings representing name of a person, etc.)

**Comment by abhabongse** [comment]
All completed by the most recent pull request #6
